apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen-image-edit-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwen-image-edit-api
  template:
    metadata:
      labels:
        app: qwen-image-edit-api
    spec:
      nodeSelector:
        gpu: h100
      initContainers:
        - name: model-downloader
          image: ghcr.io/aihpi/recreate-goods-edit-api:latest
          command: ["python3", "download_model.py"]
          volumeMounts:
            - name: model-storage
              mountPath: /app/model
      containers:
        - name: api
          image: ghcr.io/aihpi/recreate-goods-edit-api:latest
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: model-storage
              mountPath: /app/model
          resources:
            limits:
              nvidia.com/gpu: 1
              memory: "32Gi" # Generous limit to avoid OOM
              cpu: "8"
            requests:
              memory: "24Gi" # Request 24GB minimum
              cpu: "4"
      volumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName: model-storage
---
apiVersion: v1
kind: Service
metadata:
  name: qwen-image-edit-api
spec:
  selector:
    app: qwen-image-edit-api
  ports:
    - port: 200 # External port
      targetPort: 8000 # Internal container port
      name: http
  type: ClusterIP
